name: hiit
description: A Timer for HIIT Workouts.

publish_to: "none"

environment:
  sdk: ">=2.16.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  shared_preferences: 2.0.15
  url_strategy: 0.2.0
  wakelock: 0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
