name: hiit
description: A Timer for HIIT Workouts.

publish_to: "none"

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  shared_preferences: 2.0.18
  url_strategy: 0.2.0
  wakelock: 0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1
  flutter_launcher_icons: 0.12.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
