name: Build IPA

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r HIIT.ipa Payload

      - uses: softprops/action-gh-release@v1
        with:
          files: HIIT.ipa
