name: Build IPA

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - name: Archive
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r HIIT.ipa Payload

      - uses: actions/upload-artifact@v3
        with:
          name: HIIT.ipa
          path: HIIT.ipa
